version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    env_file: ./.env.dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend/src:/app/src
      - ./shared/dist:/app/node_modules/shared
      - ./backend/test:/app/test
    depends_on:
      - db
      - redis
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    env_file: ./.env.dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend/src:/app/src
      - ./shared/dist:/app/node_modules/shared
    depends_on:
      - backend

  db:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432

  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file: ./.env.dev
    command: redis-server --requirepass ${REDIS_PASS} --port ${REDIS_PORT}

  rabbitmq:
    image: rabbitmq:3.12.3-management
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
    env_file: ./.env.dev
